import { GalleryEditor } from "@/components/admin/editor-forms";
import { listAllGalleryItems } from "@/lib/content";

export default async function AdminGalleryPage() {
  const gallery = await listAllGalleryItems();
  return (
    <main className="w-full max-w-full overflow-x-hidden px-5 py-20 sm:px-10 sm:py-28 lg:px-16 lg:py-36"><div className="mx-auto max-w-[96rem]"><div className="grid gap-8 border-b border-white/10 pb-12 lg:grid-cols-12 lg:items-end"><div className="lg:col-span-8"><p className="text-xs font-semibold tracking-[0.18em] text-[#d7ff5a] uppercase">Living gallery</p><h1 className="mt-5 max-w-6xl text-[clamp(3rem,5vw,6rem)] leading-[0.9] font-medium tracking-[-0.075em]">Build the visual memory.</h1></div><p className="max-w-md text-sm leading-7 text-white/50 lg:col-span-4">Upload an image, give it context, and decide whether the class should see it now or later.</p></div><div className="mt-14 grid gap-12 lg:grid-cols-12"><section className="lg:col-span-7"><h2 className="text-2xl font-medium tracking-[-0.05em]">New gallery frame</h2><p className="mt-2 mb-6 text-sm text-white/45">An image is required before the frame can be saved.</p><GalleryEditor /></section><aside className="lg:col-span-5"><h2 className="text-2xl font-medium tracking-[-0.05em]">Existing frames</h2><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-1">{gallery.length === 0 ? <div className="rounded-2xl border border-dashed border-white/15 p-6 text-sm text-white/45">No gallery frames yet.</div> : gallery.map(({ gallery: item, imageUrl }) => <div key={item.id} className="group flex gap-4 rounded-2xl border border-white/10 bg-white/[0.045] p-3"><div className="h-20 w-24 shrink-0 overflow-hidden rounded-xl bg-cover bg-center transition-transform duration-700 group-hover:scale-105" style={imageUrl ? { backgroundImage: `url(${imageUrl})` } : undefined} /><div className="min-w-0 py-1"><p className="truncate font-medium">{item.title}</p><p className="mt-1 text-xs text-white/40">{item.category} · {item.status}</p></div></div>)}</div></aside></div></div></main>
  );
}
