import { StoryChapterEditor, StoryMemoryEditor, StoryStatEditor } from "@/components/admin/editor-forms";
import { listAllStoryContent } from "@/lib/content";

export default async function AdminStoryPage() {
  const [chapters, memories, stats] = await listAllStoryContent();
  return (
    <main className="w-full max-w-full overflow-x-hidden px-5 py-20 sm:px-10 sm:py-28 lg:px-16 lg:py-36"><div className="mx-auto max-w-[96rem]"><div className="grid gap-8 border-b border-white/10 pb-12 lg:grid-cols-12 lg:items-end"><div className="lg:col-span-8"><p className="text-xs font-semibold tracking-[0.18em] text-[#d7ff5a] uppercase">Editorial chronicle</p><h1 className="mt-5 max-w-6xl text-[clamp(3rem,5vw,6rem)] leading-[0.9] font-medium tracking-[-0.075em]">Shape the story behind the frames.</h1></div><p className="max-w-md text-sm leading-7 text-white/50 lg:col-span-4">Chapters, inside lore, and the numbers that make four years legible.</p></div><div className="mt-14 grid gap-12 lg:grid-cols-12"><section className="lg:col-span-7"><h2 className="text-2xl font-medium tracking-[-0.05em]">New chapter</h2><p className="mt-2 mb-6 text-sm text-white/45">Separate narrative paragraphs with a blank line and courses with a new line.</p><StoryChapterEditor /></section><aside className="lg:col-span-5"><h2 className="text-2xl font-medium tracking-[-0.05em]">Existing chapters</h2><div className="mt-6 space-y-3">{chapters.length === 0 ? <div className="rounded-2xl border border-dashed border-white/15 p-6 text-sm text-white/45">No chapters yet.</div> : chapters.map((chapter) => <div key={chapter.id} className="rounded-2xl border border-white/10 bg-white/[0.045] p-4"><div className="flex items-center justify-between gap-4"><p className="font-medium">{chapter.title}</p><span className="text-xs text-[#d7ff5a]">{chapter.status}</span></div><p className="mt-1 text-xs text-white/40">{chapter.level} · {chapter.year}</p></div>)}</div></aside></div><div className="mt-20 grid gap-12 border-t border-white/10 pt-16 lg:grid-cols-2"><section><h2 className="text-2xl font-medium tracking-[-0.05em]">Class memory</h2><p className="mt-2 mb-6 text-sm text-white/45">Add the lore that sits between the official milestones.</p><StoryMemoryEditor /></section><section><h2 className="text-2xl font-medium tracking-[-0.05em]">Class statistic</h2><p className="mt-2 mb-6 text-sm text-white/45">Small facts, carefully framed.</p><StoryStatEditor /></section></div><div className="mt-16 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{memories.map((memory) => <div key={memory.id} className="rounded-2xl border border-white/10 bg-white/[0.045] p-4"><p className="text-xs text-[#d7ff5a]">{memory.category}</p><p className="mt-2 font-medium">{memory.title}</p></div>)}{stats.map((stat) => <div key={stat.id} className="rounded-2xl border border-[#d7ff5a]/20 bg-[#d7ff5a]/8 p-4"><p className="text-3xl font-medium tracking-[-0.06em] text-[#d7ff5a]">{stat.value}</p><p className="mt-2 text-xs text-white/50">{stat.label}</p></div>)}</div></div></main>
  );
}
